### ISSUE TITLE
Initializing MagicDrawManager.baseHTTPURI

### ISSUE THREAD

**Issue by lq3** [ld4mbse/oslc-adapter-magicdraw-sysml#2]
Hello,

I am trying to run OSLCClient4GettingSysMLBlock as a Java application in Eclipse, but it fails to initialize MagicDrawManager. 

Exception in thread "main" java.lang.ExceptionInInitializerError
	at edu.gatech.mbsec.adapter.magicdraw.application.MagicDrawManager.<clinit>(MagicDrawManager.java:122)
	at edu.gatech.mbsec.adapter.magicdraw.clients.HTTPClient4GettingResourceRepresentation.main(HTTPClient4GettingResourceRepresentation.java:42)
Caused by: java.lang.NullPointerException
	at edu.gatech.mbsec.adapter.subversion.SubversionManager.<init>(SubversionManager.java:24)
	at edu.gatech.mbsec.adapter.magicdraw.services.OSLC4JMagicDrawApplication$3.start(OSLC4JMagicDrawApplication.java:421)
	at edu.gatech.mbsec.adapter.magicdraw.services.OSLC4JMagicDrawApplication.readDataFirstTime(OSLC4JMagicDrawApplication.java:426)
	at edu.gatech.mbsec.adapter.magicdraw.services.OSLC4JMagicDrawApplication.<clinit>(OSLC4JMagicDrawApplication.java:233)
	... 2 more

How to initialize the HTTPUI correctly ?

Best regards

**Comment by axelreichwein** [comment]
You have probably wrongly configured the OSLC adapter [configuration file](https://github.com/ld4mbse/oslc-adapter-magicdraw-sysml/blob/master/edu.gatech.mbsec.adapter.magicdraw/oslc4jmagicdraw%20configuration/config.properties). Could you make sure that syncWithSvnRepo = false

Furthermore, it is safer to test the adapter using clients located [here](https://github.com/ld4mbse/oslc-adapter-magicdraw-sysml/tree/4d40708d7e6c68a7640b27c438969123a96fb77c/edu.gatech.mbsec.adapter.magicdraw.clients/src/main/java/adapter)
